# Each route describes how an incoming URL is going to be processed by Platform.sh.
"https://epontech.com/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true

      # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://www.epontech.com/":
    type: redirect
    to: "https://epon.com.br/"